### ISSUE TITLE
Feature request: Bottom Sheet Design System

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1014]
### Is your feature request related to a problem?

Probably similar to the "Drawer" component we have now

https://xmtp-labs.slack.com/archives/C07NSHXK693/p1729142388679069

**Comment by covrter** [comment]
https://www.figma.com/design/PUfpkzt9dFX5GR1U1Fw3mQ/Converse-Global-Styles?node-id=108-1932&t=BpR839Kvc04nzHlV-1

bottom sheet draft components here (not actually figma-componentized)
