### ISSUE TITLE
Search Feature Reorganization

### ISSUE THREAD

**Issue by technoplato** [ephemeraHQ/converse-app#1050]
### Guidance on File Creation

When reorganizing or creating new features, refer to the ADR for detailed instructions on when to create specific files. Here's a quick reference:

- Create `[featureName].screen.tsx` for top-level components that encapsulate entire device screens.
- Use `[featureName].nav.tsx` for navigation components.
- Implement `[featureName].store.ts` for data stores using Zustand.
- Use `[featureName].queries.ts` for React Query functionality.
- Create `[featureName].utils.ts` for feature-specific utility functions.
- Implement `[featureName].data.ts` for data models or types.
- Use `[featureName].actor.ts` for state machines or actors controlling feature behavior.
- Create `[featureName].client.ts` to encapsulate feature behavior and control dependencies.
- Implement `[featureName].types.ts` for TypeScript types specific to the feature.

Not every feature will require all of these files. Create them as needed based on the feature's complexity and requirements.

For full details, refer to the ADR:
[ADR-001: Feature-Based Folder Structure](https://github.com/ephemeraHQ/converse-app/blob/main/adr/adr.001.folder%20and%20file%20structure/adr.001.folder%20and%20file%20structure.md)

### Tasks

- Move relevant files from `components/`, `screens/`, `hooks/`, `utils/`, and `data/` to `features/search/`
- Update import paths in moved files
- Rename files to follow new convention (e.g., `search.screen.tsx`, `search.nav.tsx`)
- Create `search.utils.ts`, `search.client.ts`, and `search.queries.ts` as needed

Key files to look for:
- `components/Search/`
- `screens/ProfileSearch.tsx`
- `utils/search.ts`
- `utils/lens.ts`

Note: Use PR #1042 (https://github.com/ephemeraHQ/converse-app/pull/1042) as a reference for the initial structure and naming conventions.

**Comment by alexrisch** [comment]
This is done
