### ISSUE TITLE
Default to Domain/Handler if No Name is Available

### ISSUE THREAD

**Issue by humanagent** [ephemeraHQ/converse-app#1112]
### Describe the bug

**Description:**

### Expected Behavior
If the domain doesn’t have a name, it should display as:
- **Name:** `earl.frens.eth`
- **Description:** not used as the name.

### Current Behavior
Currently, domains that lack a name but have a description may mistakenly display the description in place of the name.

### Potential Impact
This could affect several domains with no name but a present description, leading to inconsistent naming practices.

### Proposed Solution
Implement a fallback to use the domain/handler as the default name if the actual name is missing, ignoring the description field in this context.

Example: https://app.ens.domains/earl.frens.eth
![CleanShot 2024-10-26 at 10 07 25@2x](https://github.com/user-attachments/assets/34a72ed7-2f48-4641-9192-001f934dc29e)

**Comment by lourou** [comment]
Already fixed by @nmalzieu with https://github.com/ephemeraHQ/converse-backend/pull/52
