### ISSUE TITLE
Bug: Search Bar Text is the same color as search bar

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1124]

**Comment by lourou** [comment]
@alexrisch is this linked to https://github.com/ephemeraHQ/converse-app/issues/1125 ?
I can't reproduce this on Android nor iOS, any hint on how to?

**Comment by alexrisch** [comment]
@lourou Yeah I think it's related, seems that certain components change themes for some reason, I wonder if maybe it's dealing with memoization of them?
Both are related, so can probably close out this one, and I have also had difficulty reproducing, but do get people reaching out about it.

It's at least seen on iOS pretty consistently by Naomi
