### ISSUE TITLE
Feature request: Composer

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1204]
### Is your feature request related to a problem?

![image](https://github.com/user-attachments/assets/873b5faf-4dcb-494a-a546-7c1b2336d858)

Loom: https://www.loom.com/share/b8a44c022d2448519fcc36aed9cf341f
Figma: https://www.figma.com/design/PUfpkzt9dFX5GR1U1Fw3mQ/Converse-Global-Styles?node-id=474-11544&t=A3S3iVwmVOrlsaah-1

This should be scoped to preparing the UI to be able to use what's shown, but not make all of the functionality for it work.
Meaning, if we _can_ match the mocks, but be able to toggle the newer features off this ticket should be complete.

A few things that are new and would require additional handling to actually work after the composer work is done:

- [Sending Multiple Attachments at once](https://github.com/ephemeraHQ/converse-app/issues/1205)
- [Voice memos](https://github.com/ephemeraHQ/converse-app/issues/1206)
- Cash requests
- Changing identities within the chat

### Additional details

Known issues of current implementation:
https://github.com/ephemeraHQ/converse-app/issues/911

Fixes to watch for:
https://github.com/ephemeraHQ/converse-app/pull/1239

**Comment by covrter** [comment]
lmao at the composer image
