### ISSUE TITLE
Feature request: Linking Improvements

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1234]
### Is your feature request related to a problem?

Umbrella Ticket for Deep Links/Linking Improvements

We need to setup a more robust and consistent deep link strategy

We should handle:
1. Linking from notifications as if using normal links
2. Waiting for hydration to finish before attempting a link, but doing it once done
3. Handling links once the app is already launched as well

We need to focus on the testability of these links and the app being resilient enough to handle bad links and loading information on demand if needed

This means:
1. Display loading if it's happening 
2. Display errors if there is an error
3. Display 404 status 

Currently Known Issues with current implementation:
https://github.com/ephemeraHQ/converse-app/issues/1182
https://github.com/ephemeraHQ/converse-app/issues/1130
https://github.com/ephemeraHQ/converse-app/issues/853

**Comment by technoplato** [comment]
Made sure handling that was already in place for iOS functions properly now - no additional logic for malformed urls etc was added
