### ISSUE TITLE
Bug: conversation.send is not a function immediately after joining a new group

### ISSUE THREAD

**Issue by technoplato** [ephemeraHQ/converse-app#1388]
### Describe the bug

https://github.com/user-attachments/assets/ee4bfa9d-0ae2-4344-826c-4c6fa711e42e

join new group
send message

conversation.send is not a function banner at bottom presented

### Expected behavior

message sent to gropu

**Comment by thierryskoda** [comment]
Can't reproduce. I think it was fixed in my recent big PR
