### ISSUE TITLE
Requests bar does not match new design

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#178]
[Zeplin](https://zpl.io/OX0KyGL)

Current scope:

- Right-align Requests link
- Segmented controller in Requests view

<img width="2390" alt="#178 - Requests bar does not match new design" src="https://github.com/user-attachments/assets/04df6bb7-abb6-4c07-9cc6-fec3c854261e">

### Actual
![Image](https://github.com/Unshut-Labs/converse-app/assets/510695/e1f3993a-a7f6-483e-86d8-16909ad1a2c3)

**Comment by darickdang** [comment]
One of the flows in the following may be out of scope, especially for this ticket, but we've previously discussed moving Message Requests into Settings or Profile and I've included a flow here that goes that route.

If we're looking for a shorter term solution to this, we can simply add a title row with "Requests" right-aligned.

Again, both of the above are included here:

![#178 - Requests bar does not match new design](https://github.com/user-attachments/assets/6351a2f7-f74b-43b7-9eb8-501c30d52e7d)

Figma link: [https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1699-8740&t=y4l53xPO9CbsUcKz-1](https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1699-8740&t=y4l53xPO9CbsUcKz-1)

**Comment by lourou** [comment]
@saulmc I am happy to implement the title row with "Requests" right-aligned.

Should we aim for this UI change for this issue, or is there a decision to implement more (Message requests in profile, Option 2 icons, etc...)?

**Comment by saulmc** [comment]
Great call @lourou. Since we aren't sure what else might change about the profile page, let's just start with the right-aligned Requests link and the segmented controller for you may know/spam. If necessary, we can revisit whether to move requests into the profile view.
