### ISSUE TITLE
Undelete a group

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#220]
See #315 MVP approach:

> - Put deleted group conversations in a sub-view like Requests/Spam that is only accessible through settings.
> - Pop an alert when a user tries to tap into a conversation from this list. Options: "View" "View and Undelete"
> - Swipe to undelete instead of swipe to delete

**Comment by alexrisch** [comment]
@saulmc Should this go into the spam conversations?
Spam becomes Spam & Trash/Spam & Deleted

**Comment by saulmc** [comment]
By combining spam and trash we'd be effectively removing the ability to delete spam, so I think we should keep these separate. #315 has a proposed MVP approach:


> - Put deleted group conversations in a sub-view like Requests/Spam that is only accessible through settings.
- Pop an alert when a user tries to tap into a conversation from this list. Options: "View" "View and Undelete"
- Swipe to undelete instead of swipe to delete
