### ISSUE TITLE
Show both members of 2-member group in default profile photo

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#286]

**Comment by darickdang** [comment]
Not sure if we can do this proposal below but let me know if it does/doesn't work:

![#286 - What should the default group profile photo be when there are 2 members_ #](https://github.com/user-attachments/assets/b6140cac-6035-4382-b7a5-e963697565c9)

Figma link: [https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1699-12755&t=y4l53xPO9CbsUcKz-1](https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1699-12755&t=y4l53xPO9CbsUcKz-1)

**Comment by alexrisch** [comment]
Dev notes:
Remove excludeSelf prop from components/GroupAvatar.tsx
Update shouldExclude logic to check for members length
Move function for memoizedAndSortedGroupMembers into a util file and add tests

**Comment by alexrisch** [comment]
@lourou This may already be done in the Feature V3 Chat, if you can help verify

**Comment by lourou** [comment]
@alexrisch I checked, and it's done in the group chat creation screen, but not in the convos list or chat screen. Working in it!
