### ISSUE TITLE
Messages are slow to load into conversations after disconnect/reconnect

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#290]

**Comment by alexrisch** [comment]
@saulmc Want to make sure I understand

Disconnecting/reconnecting - Logging out of the wallet and also clearing the DB?
Were the messaging that were slow to load related to groups/1:1/both?

**Comment by saulmc** [comment]
This was reported by Shane with a clean db on his first use of the prod TestFlight. I think we can consider this issue stale.
