### ISSUE TITLE
Improved request filtering for group invites

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#316]
From Caroline:
> Flagging it could be difficult for new group members to know if they have been added to a group if it shows in spam folder since their requests folder shows "0" and group chat can only be found if they actively are looking in the requests folder to see that there is in fact a chat in the spam folder.

Let's think about this through the lens the entire requests flow and the work we are doing to reorganize it for onchain identity.

**Comment by alexrisch** [comment]
Closing this out as we've had design updates that help better solve this

Probably still something we want to generally improve, but larger than the scope of this ticket
