### ISSUE TITLE
Push notifications after deleted account

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#342]
Slack discussion:

> Alex Risch
>   19 hours ago
> Ok, yeah should be included when deleting the account to stop listening to the topics and also handle them without crashing
> 
> 
> Noé Malzieu
>   [12 hours ago]
> When you delete the account we tell the backend to unsubscribe the push token but it could have not happened if you just deleted the app
> Also, push notifications received for unknown topics (or topics for a logged out account) should drop the notification but we can’t drop notifications on ios preview :)
> Of course it should still not crash.

**Comment by alexrisch** [comment]
Closing this as it's mostly a preview issue, not production
