### ISSUE TITLE
Group Admin 'Add Member' Should Skip 1:1 Prompt

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#346]
Expected Behavior: To add a group member to the group chat
Actual Behavior: received a prompt to start a 1:1 chat with recommended users
Steps to Reproduce: Ad an admin, "add group member', see recommendations for 1:1 chats when searching for username.

"Add group member" from Group Admin should skip prompt to start 1:1 conversation

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1721686838774259)

**Comment by saulmc** [comment]
@lourou Could we simply change the "Chat" button next to each recommendation to "Add" in this context, rather than removing the recommendations altogether?

**Comment by lourou** [comment]
@saulmc Got it! Only for new group chats, or also when adding new members to an existing group chat?

**Comment by saulmc** [comment]
Good question. How about show recommendations for new chats only? Since the recommendation engine right now has no idea who is already in a group chat, it's probably a lot less useful than it should be for adding folks to existing chats.

**Comment by lourou** [comment]
@saulmc just implemented profile recommendation for new group chats! You may now add a recommended user, when added (either via search or Add button), it is removed from the list to avoid duplicates.

Video:

https://github.com/user-attachments/assets/e37a0800-42bd-4420-9500-577bccfd644d

**Comment by saulmc** [comment]
@lourou Nice! Nit: I noticed the "Recommended profiles" list title disappeared when you tapped "New Group".
