### ISSUE TITLE
App Crash and Stuck in Login Loop

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#356]
Expected Behavior: Select the intended wallet to use to sign in to Converse, complete signatures, use app. 
Actual Behavior: 
Stuck in a signature loop attempting to log back into the app. 
Simultaneously experiencing Converse App crashes during this process. 
Only way to exit this loop is to kill the app
- Coinbase Wallet and Metamask (iOS)
- Coinbase (Android)
- Connected via Desktop (iOS) - after completing step 2/3 (scanning QR Code, the user experienced a white screen. 

How to recreate: Attempt to connect to Converse via Coinbase/Metamask wallet. 

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1721780367773909?thread_ts=1721780367.773909&cid=C07DX271K6V)

**Comment by nmalzieu** [comment]
Reopening the task as there are some improvements that could come from an SDK update
