### ISSUE TITLE
Conversation deleted, new messages not appearing in list (Android)

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#357]
Conversation was deleted, then new message sent to it and it did not appear in conversation list

Expected Behavior:
• New messages sent to a deleted conversation should be received normally.
• Names should display correctly after reopening the app.
Actual Behavior:
• Deleted conversation is gone as expected, but new messages (text and photo) are not received.
• Chats only appear in the message list after initiating a new chat and sending a message to that wallet address.
Steps to Reproduce:
1. *Delete a Conversation:*
    ◦ Delete an existing conversation.
2. *Receive New Messages:*
    ◦ New messages are sent to the deleted conversation.
3. *Log Back In:*
    ◦ Log out and back in.
    ◦ Deleted conversation is gone, but new messages are not received.
4. *Search and Start Chat with Wallet Address:*
    ◦ Search for the sender’s wallet address.
    ◦ Start a chat and send a message.
• The chat appears in the message list and previously sent messages appear in the chat. 

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1721784329320869)

**Comment by nmalzieu** [comment]
@CarolineMMcGuire @saulmc "deleting" a conversation is a converse specific feature (not part of the protocol) which basically hides it forever inside Converse so the behaviour you're seeing is expected and this is not a bug.
This information being saved in the converse backend, loggout out & back in should have no effect (convo still hidden).

We might want to explain that to the user in a popup? We introduced this before consent & blocking existed. Maybe we just want to remove that feature?

If there has been product discussions about changing that feature to the one that @CarolineMMcGuire expected (i.e. logging out & back in restores the convo + new messages in a deleted convo "undelete" it), let me know, but it's more work!
