### ISSUE TITLE
Implement a "sync this group" notification type

### ISSUE THREAD

**Issue by nmalzieu** [ephemeraHQ/converse-app#362]
Some notifications for some commit messages (adding and removing users in a big group) would also be big enough to go over Apple's limit.

Let's catch it and just send a "sync group" notification which might help with forked state

**Comment by alexrisch** [comment]
@nmalzieu trying to clean up some of these older issues

I believe we already catch most of these from a push notification perspective (correct me if I'm wrong), but we are not doing syncing only notifications

My understanding of this is is for messages like group updates (member or metadata changes), we will want to sync the group 

Is that understanding correct?

**Comment by nmalzieu** [comment]
@alexrisch yes sometimes the group change notification payload is bigger than APNS / FCM's payload max size and so it fails

We could probably
- compute size of the payload before sending it rather than waiting for it to fail
- when size of the payload is bigger than size limit, send a new kind of notification that just syncs the group

Maybe we can be smarter than that and also understand during the sync what the latest event was and still show a notification but more work for sure

**Comment by alexrisch** [comment]
@nmalzieu thank you for the background info, I'll add additional details and add it to the backlog, assigning back to me for now

**Comment by alexrisch** [comment]
### Dev Direction:

## iOS
Update ios/ConverseNotificationExtension/NotificationService.swift to handle new type from backend changes
Add new function to handle syncing the appropriate group for the account and silencing the push notification

## Android
Update android/app/src/main/java/com/converse/dev/NotificationParser.kt to parse new type from backend changes
Add new function to handle syncing the appropriate group for the account and silencing the push notification

**Comment by alexrisch** [comment]
This is merged and ready to be enabled on the backend with wider 2.0.7 take rate
