### ISSUE TITLE
Refactor: Containers and Dumb Components

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#387]
### Is your feature request related to a problem?

As user groups and messages scale up & the potential of developers to contribute to a codebase without a lot of background knowledge, introducing re-renders currently has serious implications on the app that developers would not think to check

### Describe the solution to the problem

Setup a new pattern to the app:

Containers - Connected components that can be used to access & manipulate data and callbacks - Controllers/View Models

Components - Dumb components, these take simple props and display/execute what is given without additional logic - Views

There is no 100% perfect way to get to this from 0%-100% but should be an end goal, whenever updating components this should be kept in mind

**Comment by saulmc** [comment]
What are some rules of thumb we can apply here? i.e. "View components should not use hooks"?

**Comment by alexrisch** [comment]
@saulmc sorry totally missed this, yes the basic rule of thumb would be:
Does this require some logic that will change real data? Yes - Should be a container, No - Should be Component
Essentially  the hooks/callbacks into  the components as "onPress" or something along those lines

It's small but helps us get closer to more distinguishable layers

**Comment by alexrisch** [comment]
This is an ongoing effort by the team since the offsite, I don't think this is really necessary to keep open as it's more a pattern to strive for
