### ISSUE TITLE
Double Tap Reaction Opens Unreadable Menu (Android)

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#395]
*Double Tap Reaction Opens Unreadable Menu (Android)*

*Double Tap Reaction Adds Heart and Opens Menu with Black Text on Black Background*
*Description:* Double tapping to add a heart reaction also opens the menu, which displays with black text on a black background.
*Expected Behavior:* Double tapping should add the heart reaction without opening the menu. The menu should display with readable text if opened.
*Actual Behavior:*
• Double tapping to add a heart reaction also opens the menu.
• The menu displays with black text on a black background, making it unreadable.
*Steps to Recreate:*
1. Double tap on a message to add a heart reaction.
2. Observe that the menu opens as well.
3. Note the black text on a black background in the menu.

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722047040083139)

**Comment by alexrisch** [comment]
Fixed with Reactions menu
