### ISSUE TITLE
Connect Account - Coinbase Wallet Connection Unsuccessful (Android)

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#396]
*Connect Account - Coinbase Wallet Connection Unsuccessful (Android)*

*Description:* There is an issue connecting accounts with Coinbase Wallet (CBW), resulting in continuous loading after the first signature.
*Expected Behavior:* The account should connect successfully without continuous loading after the first signature.
*Actual Behavior:*
• The first signature is completed successfully on both CBW and Converse.
• Once the Converse signature is selected, the Converse app continuously shows loading and does not complete the connection process.
*Steps to Recreate:*
1. Attempt to connect an account using Coinbase Wallet.
2. Complete the first signature on both CBW and Converse.
3. Select the Converse signature.
4. Observe the continuous loading issue on the Converse app.

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722046954689379)

**Comment by saulmc** [comment]
@CarolineMMcGuire Is this still happening in 233?

**Comment by CarolineMMcGuire** [comment]
@saulmc This is resolved in 233! I was able to connect to Coinbase with no issues on Android!

**Comment by saulmc** [comment]
Thanks @CarolineMMcGuire ! Could you do a quick scan of the issues list for any others that you feel confident closing as of 233?
