### ISSUE TITLE
"Member Added" Messages and Incorrect Member List in Group Chat

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#397]
*"Member Added" Messages and Incorrect Member List in Group Chat*
_noting that this is not for every group chat but I did experience this for this certain example_

*Description:* When added to a group chat, there are no "member added" messages, and the member list displays incorrectly.
*Expected Behavior:*
• "Member added" messages should be visible at the beginning of the chat.
• The member list should display all members correctly.
*Actual Behavior:*
• No "member added" messages appear at the beginning of the chat.
• The member list only shows the user’s name as a group member, even though they did not create the chat.
• The user is shown as a super admin and the only member.
*Steps to Recreate:*
1. Be added to a group chat.
2. Check the beginning of the chat for "member added" messages.
3. View the members list for the group chat.
<https://xmtp-labs.slack.com/files/U04ASD4HTA9/F07E48LRXHU/rpreplay_final1722034866.mov>

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722044036928359)

**Comment by nmalzieu** [comment]
@CarolineMMcGuire is that something you still experience or can we close it?

**Comment by alexrisch** [comment]
Can no longer recreate
