### ISSUE TITLE
Message in Group Chat Displayed Incorrectly on Different Devices

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#399]
*Message in Group Chat Displayed Incorrectly on Different Devices*

*Description:* There is an issue where a sent message in a group chat displays inconsistently across different devices.
*Expected Behavior:* Messages sent in a group chat should display correctly with the appropriate sender information on all devices.
*Actual Behavior:*
• A message sent in a group chat appears correctly on one device.
• On another device, the same message shows up as if it was sent from someone else but with the correct username.
• Leaving the chat and returning fixes the display issue.
*Steps to Recreate:*
1. Send a message in a group chat.
2. Check the message on another device.
3. Observe the discrepancy in sender information.
4. Leave the chat and return to see the message display correctly.
<https://xmtp-labs.slack.com/files/U04ASD4HTA9/F07EAPTT37D/screenshot_2024-07-26_at_5.28.34___pm.heic>
<https://xmtp-labs.slack.com/files/U04ASD4HTA9/F07EPH9GEU9/screenshot_2024-07-26_at_5.28.25___pm.heic>

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722043949018969)

**Comment by nmalzieu** [comment]
Should be fixed by the recent group members libxmtp fix!
