### ISSUE TITLE
Bug: App Onboarding Forced an Existing User to Create a Converse Profile again

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#412]
### Describe the bug

Logging into the same wallet has displayed the profile creation screen again

### Expected behavior

If a user has already created a Converse profile they should not have to make another one

**Comment by neekolas** [comment]
This is me, if anyone needs help reproducing

**Comment by saulmc** [comment]
@CarolineMMcGuire have you been able to reproduce this one?

**Comment by CarolineMMcGuire** [comment]
Hey @saulmc - no this has not happened to me! Looks like @neekolas is able to help with reproducing if needed!

**Comment by saulmc** [comment]
@neekolas are you still able to repro this?

**Comment by neekolas** [comment]
Wiped last night and it didn't ask me to create a new profile, so think we can close.
