### ISSUE TITLE
Ability to search emojis for reactions

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#427]
Enhancement - Ability to search emojis for reactions - [Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722369971072549) - [Zeplin](https://zpl.io/NEwQN3v)

<img width="662" alt="Screenshot 2024-08-25 at 11 32 48 PM" src="https://github.com/user-attachments/assets/36424f13-b9d4-4bef-b7c6-f5df69717d99">

**Comment by darickdang** [comment]
There's a lot here so we may need to tone down the depth of what I'm proposing but even without the "Customize" options, we can still use the designs here.

![#427 - Ability to search emojis for reactions](https://github.com/user-attachments/assets/14d2b038-aea3-41d8-ad6a-fc542b41e9bc)

Figma link: [https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1699-15229&t=y4l53xPO9CbsUcKz-1](https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=1699-15229&t=y4l53xPO9CbsUcKz-1)

**Comment by saulmc** [comment]
Rather than changing the design of the third party lib, we should reimplement natively in a drawer component.

**Comment by saulmc** [comment]
Here is the Zeplin for the above: [Zeplin](https://zpl.io/NEwQN3v)

"Advanced/Optional" screens are not in scope today.
