### ISSUE TITLE
InboxID showing in reply and notification instead of username

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#431]
Seeing Naomi’s inboxId here. Also, I didn't get a screenshot, but the push notification for Rich's message just now showed as from an inboxId too.

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722362923651789?thread_ts=1722362923.651789&cid=C07DX271K6V)

**Comment by nmalzieu** [comment]
Should be fixed by the recent group members libxmtp fix!
