### ISSUE TITLE
Group Chat Name Text Cut Off on Group Information Page

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#449]
Group Chat Name Text Cut Off on Group Information Page

Description:
On the group information page for group chats, the Group Chat Name text is being cut off. This makes it difficult to read the full name of the group chat.

Steps to Reproduce:

Open the group chat.
Navigate to the group information page.
Observe the Group Chat Name text.
Expected Result:
The Group Chat Name should be fully visible and not cut off.

Actual Result:
The Group Chat Name text is cut off.

Android Pixel 7

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1722556809222929)

**Comment by alexrisch** [comment]
Now we show ellipsis so it's not totally cut off
Going to close this out until we have updated designs for that screen
