### ISSUE TITLE
Usernames in 1-to-1 Conversations Revert to InboxID/0x Addresses After Logout and Login

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#471]
Usernames in 1-to-1 Conversations Revert to InboxID/0x Addresses After Logout and Login

*Description:*
Initially, the 1-to-1 conversations in the conversation list displayed the correct usernames. However, after logging out and logging back in, the 1-to-1 conversations reverted to showing InboxID/0x addresses instead of usernames.

*Steps to Reproduce:*
1. Log in to the application.
2. Verify that 1-to-1 conversations display the correct usernames.
3. Log out of the application.
4. Log back in to the application.
5. Observe the conversation list.
*Expected Behavior:*
1-to-1 conversations should display the correct usernames even after logging out and logging back in.

*Actual Behavior:*
1-to-1 conversations display InboxID/0x addresses instead of usernames after logging out and logging back in.

*Time of Occurrence:*
9:21 PM CDT

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1723036569260619)

**Comment by technoplato** [comment]
@alexrisch which commit closed this?
