### ISSUE TITLE
Testing "Block User" Functionality

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#487]
Testing "Block User" Functionality

Description
When blocking a user from their profile, the conversation remains in the conversation list initially. However, the conversation is removed from the list only after the app is killed and reopened.

Steps to Reproduce
1. Open the app and go to the conversation list.
2. Select a user and navigate to their profile.
3. Block the user.
4. Observe that the conversation with the blocked user remains in the conversation list.
5. Kill the app and reopen it.
6. Observe that the conversation with the blocked user is now removed from the conversation list.
7. 
Expected Behavior
• The conversation should be removed from the conversation list immediately after blocking the user, without needing to kill and reopen the app.
Actual Behavior
• The conversation remains in the conversation list until the app is killed and reopened.

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1723155169839429)

**Comment by alexrisch** [comment]
Fixed with https://github.com/ephemeraHQ/converse-app/pull/539
