### ISSUE TITLE
ClientError.creationError: No v3 keys found, you must pass a SigningKey in order to enable alpha MLS features

### ISSUE THREAD

**Issue by nplasterer** [ephemeraHQ/converse-app#500]
https://converse-app.sentry.io/issues/5592194575/events/97c20b7f7be84d34ac60b0b47bf93b45/?project=4504757120729088

It appears for some reason sometimes a converse client is being created without getting all the necessary signatures to create the V3 client before calling create from keyBundle.

**Comment by alexrisch** [comment]
Duplicate of https://github.com/ephemeraHQ/converse-app/issues/884
