### ISSUE TITLE
Validate login flows with no existing V3 keys 

### ISSUE THREAD

**Issue by nplasterer** [ephemeraHQ/converse-app#503]
The app won't work without a V3 key.

- Validate SDKs appropriately error if V3 key fails to create.

**Comment by nplasterer** [comment]
Just adding a note here that Nick noted that a third signature and forced logout may not be required. We should validate this in testing before release.

**Comment by nplasterer** [comment]
This is related to https://github.com/ephemeraHQ/converse-app/issues/413

**Comment by nplasterer** [comment]
If a flag for any reason is not passed that would be the only reason a V3Client would be null. I think we can close this out after @CarolineMMcGuire validates the flow of logging in on a pre-existing V2 key with no V3 keys.

**Comment by CarolineMMcGuire** [comment]
@nplasterer - confirming this has been tested and successful. I will close this!
