### ISSUE TITLE
Bug with "Group Invite Link"

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#526]
Not working correctly on both iOS and Android. Unable to join group chat from the copied link. 

I am having trouble testing the Group Chat Invite Link - Is it correct that I would copy the link, send it to someone (in converse) and then should be able to click the link to join? _I have tried pasting the link in the search bar for new chat + group chat._

Once I send the link, nothing happens when it is clicked, it's not like a URL that I can click and open something else. Let me know if I'm missing something/testing this incorrectly!

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1724094110291119?thread_ts=1724094110.291119&cid=C07DX271K6V)

**Comment by alexrisch** [comment]
Sorry this was my fault for not communicating the current state as some things still need to get deployed

If you take the link that gets copied for example: undefined/group-invite/ktnrFvAcHY_JMNkuT2cjY
paste it in the notes app and change to to converse://groupInvite/ktnrFvAcHY_JMNkuT2cjY
It should work

However in some testing it seems like Android is not working, so taking a look into that right now

**Comment by alexrisch** [comment]
Issue we were seeing should be fixed in https://github.com/ephemeraHQ/converse-app/pull/531
