### ISSUE TITLE
Feature Flagging

### ISSUE THREAD

**Issue by nplasterer** [ephemeraHQ/converse-app#527]
Lets start a discussion around adding feature flags for things going forward so we can roll them back if needed.

**Comment by lourou** [comment]
Open questions:
1. Do we control flags via backend or directly in the code?
2. Third-party service or develop a custom solution in our backend or codebase?
3. Segment by user roles, app version, testing groups, or something else?

Risks considerations:
- Increased code complexity
- Maintenance of managing technical debt from leftover flags
- Data privacy, as we might want to store minimal data from users on our end

**Comment by alexrisch** [comment]
I think given that we want devs to be able to work on top of the app I am really favoring a local user config that they can set

Examples of this would be transaction frames

It would be off by default, and when used we would notify the user to update their config to enable it

**Comment by alexrisch** [comment]
Examples of other features we would put in this:
1. Blocked user messages in group chats: "hidden" | "view_on_toggle" | "shown"
2. Transaction frames
3. Default emojis
4. Default double tap emoji, or default functionality on double tap
5. Download images automatically
6. Send read receipts
