### ISSUE TITLE
Feature request: Add ability to revoke Installations

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#543]

**Comment by nmalzieu** [comment]
@saulmc product question

- to revoke installations for an inbox, you need to sign with the wallet that owns that inbox
- currently Converse can only be linked to one wallet : meaning if you want to revoke installations for inbox A - then for inbox B, you have to connect with different wallets. Is that ok for now (seems pretty edge)

Also, we'll want at some point a place where you can
- see the current wallet app / wallet id that is currently linked to Converse
- disconnect
- connect a new one (right now the connect drawer appears only when you click on "Revoke other installations"

That work can be part of that PR or the transactional frames one that I could start right after, what do you think?
