### ISSUE TITLE
Alert user when 2nd+ installation requires logout for v3 upgrade

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#567]
Decision: Log out or prompt for a 3rd signature

**Comment by saulmc** [comment]
This happens automatically for the first installation, but requires logout for subsequent installations.

**Comment by nmalzieu** [comment]
@saulmc Are we just showing an alert like that?
Want to give me a wording? Or do we want to show a fullscreen specific screen?


![Image](https://github.com/user-attachments/assets/6bb1c105-f0dc-470f-944d-0594a69fdbd0)

**Comment by saulmc** [comment]
Now that I see this, what would you think about just triggering the auto-logout right away without an alert message? That isn't unexpected after a major app update.

**Comment by nmalzieu** [comment]
> Now that I see this, what would you think about just triggering the auto-logout right away without an alert message? That isn't unexpected after a major app update.

I can try! It takes a few seconds before we detect this so the user would still see the Converse interface but might be ok especially since it's only once, for people with multiple devices logged into v2.
