### ISSUE TITLE
Glowup and include context on group invite landing page and unfurl

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#581]
- [x] Group Invite design styling on mobile
- [x] Troubleshoot the `onXmtp` and `canMessage` variables to display the buttons vs links to the App Store
- [x] Group Invite design styling on desktop
- [x] Adapt DM screen with the same styling on mobile
- [x] Adapt DM screen with the same styling on desktop
- [x] Update "Identity not found" screen, and "Groupe invite not found" screen 
- [x] Design and implement the og:image/frame

**Comment by darickdang** [comment]
I'm not sure if I understand the logged in/logged out states correctly but here's what I got.

We should make this look similar to how they look in the app but pop the Converse logo with the word "Converse" on the web view.

<img width="1440" alt="Desktop" src="https://github.com/user-attachments/assets/e2a01c57-f16c-42e8-afe0-2f38d7b2dea8">

<img width="393" alt="Mobile - With App" src="https://github.com/user-attachments/assets/26502457-97cd-4528-a214-57df8573413c">

<img width="393" alt="Mobile - No App" src="https://github.com/user-attachments/assets/bfe9eba3-b62a-4546-bacb-65e3c694da1a">

**Comment by saulmc** [comment]
@lourou would you be able to look into this [Converse website ](https://github.com/ephemeraHQ/converse-website) request after the requests UI work is complete? I've added you to the repo

I believe the group context info is all available. If not, we can descope from the designs rather than invest in piping it through.

This should also extend to the opengraph metadata when one of these links is shared. Ideally, these links unfurl and include all of the above context information in an approximately equivalent design.

**Comment by lourou** [comment]
@saulmc sure thing, will look into this!

**Comment by lourou** [comment]
@saulmc do we want to generate on the fly and show a custom `og:image` containing the group icon, converse logo and group description inside the image, so that users see this when shared?

**Comment by lourou** [comment]
Hey @darickdang, I just finished implementing the group invite styling on mobile. Here's a preview on an iPhone 15 Pro screen. I also made sure it fits on iPhone SE and Mini. Do you see anything that needs to be changed?

<img src="https://github.com/user-attachments/assets/ae3cce9a-84b4-4fa9-ab8f-ae00cc61c400" width=350" />

**Comment by lourou** [comment]
thanks @saulmc 🙌 

re: the generic `og:image` loading loop issue inside the app, [I created the issue here](https://preview.converse.xyz/)
