### ISSUE TITLE
'Profile' and 'Modify Profile' pages are inconsistent

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#61]
Reported by Brian:

|Profile|Modify Profile|
|-|-|
|![BAF2AA10-34A8-48C9-932A-E4AD3904FE30_1_102_o](https://github.com/Unshut-Labs/converse-app/assets/510695/176e7fd0-c00f-49cc-9560-067859792269)|![D7F1AA37-9BB0-47B1-829A-0CD2BB277446_1_102_o](https://github.com/Unshut-Labs/converse-app/assets/510695/d18de427-ae25-4f9b-895f-39070112695f)|

**Comment by alexrisch** [comment]
@saulmc I'm thinking we can close this out as we are largely revamping the app

**Comment by saulmc** [comment]
Yep, works for me @alexrisch .
