### ISSUE TITLE
Deploy today's live Converse web app on dev network

### ISSUE THREAD

**Issue by jhaaaa** [ephemeraHQ/converse-app#613]
### Is your feature request related to a problem?

This came up because the subscribe/broadcast tools that Alex built and deployed are, correctly, running on the dev network. 

It would be great to have a web app that supports consent on the dev network so people using these tools can test their work. 

And in general, it would be great to have this web app running on dev.

### Describe the solution to the problem

Please deploy https://app.converse.xyz/conversation to the dev network.

Specifically, this is the version of the Converse web app that is live today. This is not a version related to the "all new" Converse app.

### Additional details

Request approved by @saulmc 🫡

**Comment by alexrisch** [comment]
@jhaaaa @saulmc I want to make sure I understand, the thought is to have a dev website pointing to dev and a the current https://app.converse.xyz/conversation pointing to prod? 

Or we want to change the current website to point to dev?

**Comment by alexrisch** [comment]
@jhaaaa this exists already at https://app-preview.converse.xyz/ :)

**Comment by jhaaaa** [comment]
Awwww yeah, @alexrisch! Thank you so much - this will do the trick! We can close this issue. 🫡
