### ISSUE TITLE
enhancement: auto-approve groups from accepted invite links

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#661]
Group chats from accepted invite links should not go to Requests. Accepting an invite link can be considered an affirmative intent to join the chat akin to approving it.

**Comment by alexrisch** [comment]
We will need to add the groupId to the invite Link Response (not opposed to this as there's some other features that need it) but just want to confirm we are ok potentially leaking that info

**Comment by nmalzieu** [comment]
@alexrisch isn't this line doing just that? https://github.com/ephemeraHQ/converse-app/blob/main/screens/GroupInvite.tsx#L55

**Comment by nmalzieu** [comment]
@alexrisch yes it works well if the group streams, and not at all (not even redirected) if the groups don't stream.
So this issue is more about groups streaming I would say?

**Comment by alexrisch** [comment]
@nmalzieu yep likely a streaming issue unless the event listener is being unmounted during a rerender and not being added back in time to correctly handle the streamed group

**Comment by nmalzieu** [comment]
Nope the group is just not streamed from my tests. Have opened a PR on RN repo with a simple failing test that might be linked to this issue

**Comment by nmalzieu** [comment]
I think I fixed the group streaming in my latest iOS PR, which has been included in latest SDK. 
Also we're not relying on streaming anymore for group invite links, should we close this? cc @alexrisch

**Comment by alexrisch** [comment]
Closing
