### ISSUE TITLE
wallet picker ui for revocation

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#694]

**Comment by darickdang** [comment]
Here's an initial pass at this:

<img width="1731" alt="#694 - Wallet picker ui for revocation" src="https://github.com/user-attachments/assets/0f16a243-9e7d-47c8-8ab9-53a1713ce09e">

**Comment by darickdang** [comment]
"Revoke all" seems like a step that could be quite dicey to try and do in this flow so that may go away.

**Comment by darickdang** [comment]
Here's an initial pass at this. "Revoke all" seems like a step that could get quite dicey to try and do in this flow so that may go away.

<img width="1731" alt="#694 - Wallet picker ui for revocation" src="https://github.com/user-attachments/assets/7f43a7d0-dd75-4d02-b24f-73c4f077e7be">

**Comment by saulmc** [comment]
Thanks @darickdang, this is great! @nmalzieu the signature is only needed one time, right? It won't be consistently part of the flow.

**Comment by nmalzieu** [comment]
Thanks @darickdang 
@saulmc I think we agreed not to have names for installations for now and to only have the "Revoke all" options?
Also, the signature is needed every time you want to revoke.
But if Converse is already connected to the wallet, you only need to connect once. The screenshots are missing the "connect" step.

**Comment by saulmc** [comment]
- Single button in profile to revoke all installations
- Hint on which wallet is the right one

**Comment by saulmc** [comment]
@nmalzieu @covrter UI for wallet picker for revocation

**Comment by covrter** [comment]
> Single button in profile to revoke all installations

Confirming that this means: I tap this, sign once, and revoke all installations EXCEPT the current one?

**Comment by covrter** [comment]
Getting close here — here's a revised version (surely I didn't get it all right … but closer?)
- https://www.loom.com/share/792795e9f19544df9db6967ceb2dd6bd?sid=f9d74ae6-7044-4fdc-b523-667c9e42bd82
- https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=2486-16973&t=GvsjjPMhSQAfiNhP-1

![image](https://github.com/user-attachments/assets/0baaabbc-9581-4fd6-8cbf-f0c3161b48a1)

**Comment by covrter** [comment]
PS @saulmc pls assign this to me (and/or assign me assigner privileges :) )

**Comment by saulmc** [comment]
@covrter done and done!

**Comment by covrter** [comment]
PS @nmalzieu @saulmc pls check the loom/layout above and lmk what else needs tweakin'

**Comment by nmalzieu** [comment]
> PS @nmalzieu @saulmc pls check the loom/layout above and lmk what else needs tweakin'

Thanks @covrter 

- @saulmc worked very recently on wording and removed the word "installation" so I guess you should work together on those screens to find the right wording!
- the "wallet" the user needs to connect with is not a "wallet app" (Coinbase Wallet / Rainbow) but a specific wallet address (0x...). It's the one that is "owner" of the XMTP account. The wording I currently use is _Connect the wallet associated with your XMTP account: 0x...._ in place of _Please reconnect this wallet to confirm_ . The list of wallet apps shows the wallet apps that are currently installed on the device. We probably need an empty state if no wallet app is installed!
- revoking app installation does not delete data on other devices immediatly (it does if the user opens Converse on the other device though) but I guess it's part of the wording that you can work on with @saulmc

**Comment by covrter** [comment]
@saulmc @nmalzieu do we know how revocation will work with SCW/Passkeys? If yes, I can design for EOA and SCW both now, so that we're ready. No prob if not, tho.

**Comment by nmalzieu** [comment]
@covrter when I revoke, I would say other devices will not be able to decrypt messages even from notifications. Is that right @neekolas ?
Then, when you open the app on that device, we detect that the installation is revoked, and we actually log you out and delete your local data, indeed.

**Comment by saulmc** [comment]
@covrter I like the idea of iterating this design towards the SCW world. For now, @nmalzieu's implementation feels good enough to ship. Here are the updated strings:


```

**Comment by saulmc** [comment]
lol misclick. did not mean to drop a comment and shut down the discussion

**Comment by alexrisch** [comment]
This is done
