### ISSUE TITLE
Add drag to reveal timestamps

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#696]
Dragging to the left anywhere inside a conversation should reveal message timestamps to the right.

When dragging to the left, messages from me should translate left accordingly, but messages from others should stay in place. This interaction can be seen in iMessage.

**Comment by lourou** [comment]
@saulmc I've implemented the tap-to-reveal timestamps feature. Let me know what you think!

Time displays are localized based on the 12/24-hour formats depending on the phone's locale.

<img src="https://github.com/user-attachments/assets/81a20895-6eec-4b2b-889c-2129144ac92f" width="350" />

**Comment by saulmc** [comment]
Thanks @lourou ! Could you please modify the animation so that the container for the timestamp expands vertically, not just the timestamp text? This will make the message list feel less jumpy in reaction to the timestamp reveal.

**Comment by lourou** [comment]
Yes @saulmc this is now smooth both animating in and out!

<img src="https://github.com/user-attachments/assets/b4b36a07-df3a-4193-ada5-e5b4d2609405" width="350" />

**Comment by saulmc** [comment]
Beautiful! Thanks!
