### ISSUE TITLE
Conversation context menu

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#727]
Replicate the context menu long press interaction on conversations as implemented in iMessage, Messenger, WhatsApp, and Telegram.

- [x] Long press a conversation in the conversation list to reveal a context menu (replaces long-press to pin)
- [x] Add "Pin" to context menu
- [x] Add "Mark as Unread" to context menu
- [x] Add "Delete" to context menu
- [x] Display auxiliary preview of the conversation

**Comment by lourou** [comment]
@saulmc do we want to display the content of the conversation on long press + the context menu below? or just highlight the conversation cell in the list + context menu below?

**Comment by saulmc** [comment]
@lourou Yep, the auxiliary preview should be the conversation, not the cell.

**Comment by saulmc** [comment]
Thank you for putting this together @lourou ! Tagging in @thierryskoda for review.
