### ISSUE TITLE
Group messages often missing until reloading conversation

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#728]
[From Caroline](https://xmtp-labs.slack.com/archives/C076F0L877T/p1726104135830509)

> For the update messages for photo/description/name messages when I updated all three (photo/name/description) only 1/3 messages showed in the chat immediately - when I went back to the conversation list and back into the chat 3/3 showed.

I encountered this as well when adding a few members to a group. Only the first member addition showed up as a group update message until I left and re-entered the conversation.

Update: Shane encountered this with normal messages, too

**Comment by saulmc** [comment]
Reopening this issue based on Caroline's report today:

> Updated photo/description/name and does not include group chat member’s name in the update. “_____ changed the group photo/name/description to “example”
Only 1/3 of the update messages showed immediately- once I left the conversation and clicked back into the conversation, all three update messages showed immediately.

**Comment by alexrisch** [comment]
This should be fixed with updated handling in V3
