### ISSUE TITLE
Bug: Null conv state doesnt clear when receive conv

### ISSUE THREAD

**Issue by cameronvoell** [ephemeraHQ/converse-app#755]
### Describe the bug

![ezgif-7-84762494ee](https://github.com/user-attachments/assets/838a1658-24d0-4d13-92b2-ff8991da945f)

### Steps to reproduce the bug

it may be that conversations that go to the requests tab can not be seen from the null state screen

When the user creates their own conversation, the null state will clear

**Comment by saulmc** [comment]
closed by #746
