### ISSUE TITLE
Requests from wrong account appear in hidden requests

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#771]
Steps to reproduce:
1. Create a group with two new ephemeral accounts
2. Switch to a preexisting account
3. Check "Hidden requests"
4. You'll see the group invite created in step 1

**Comment by saulmc** [comment]
Should be fixed with: https://github.com/xmtp/xmtp-react-native/issues/495

**Comment by nmalzieu** [comment]
@saulmc should we close that one?
