### ISSUE TITLE
Group consent modal does not dismiss after accepting

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#772]
Prompting me to accept contact and then not letting me accept 

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1726675743322809)

**Comment by alexrisch** [comment]
User is no longer seeing this

Root issue is that this was showing the DM consent popup rather than the group, which is a littler concerning and related more to how the conversations are being normalized or stored
