### ISSUE TITLE
unresponsive during initial sync

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#799]
Slow initial sync blocks UI updates other than the requests count.

Described by Shane on Android below:
> - Was stuck on the null state screen for 15 seconds I thought I lost all my convos
> - I’ve been syncing my inbox for about 5 minutes and it just keeps counting requests
> - I was stuck at 359 requests for 30 seconds and then a few messages finally loaded but all old ones and now I’m just still waiting

Described by another Android tester:
> my inbox is still loading after 20 minutes - the only indication of progress is a slow upcount of my requests.
the app is really slow right now since its loading the inbox.

On iOS, I've encountered a UI lockup while initial loading is taking place, but only for 2-3 seconds.

**Comment by alexrisch** [comment]
This a pretty large fix in my opinion and I think we need to plan this out from a number of perspectives

1. What's the preferred UX for a **large** inbox (let's assume thousands)
2. Do we feel from a technical perspective that we can handle thousands of conversations on initial load? (I think right now the answer is no)
3. Is this an android specific issue right now?

We need ways to test this and verify which is fairly hard with how the current data layer is setup

**Comment by saulmc** [comment]
To clarify, this issue is in regards to the app being unresponsive during the sync. I've updated the title accordingly.

**Comment by nmalzieu** [comment]
@alexrisch agreed that whatever the issue we can't do magic for how long the initial sync of 1:1 messages take to load from the network
However, if I understand @saulmc correctly, this is something pretty recent, when 1:1 conversations load the app is unusable. I'll investigate this morning!
