### ISSUE TITLE
remove default exports; add lint rule for preventing them in the future

### ISSUE THREAD

**Issue by technoplato** [ephemeraHQ/converse-app#824]
default exports make tracking down dependency chains harder and that's bad

[slack thread](https://xmtp-labs.slack.com/archives/C07NSHXK693/p1728319195105829)

![Image](https://github.com/user-attachments/assets/f47493f8-12a2-4069-89ea-9007a9b1c485)

**Comment by alexrisch** [comment]
Lint rule is added, will tackle incrementally afterwards
