### ISSUE TITLE
Feature request: Group Join Request Error Handling Improvements

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#850]
### Is your feature request related to a problem?

When a group join request fails the admin is not notified and is blissfully unaware others would like to join

### Describe the solution to the problem

When a user receives a Group Join Request we should silence the push notification if it works and everything is successful
If it fails then we should show the user the push and probably want to navigate them to the Group to begin Management
Finally we should have some UI to indicate to the admin that there is a pending request

**Comment by nmalzieu** [comment]
@alexrisch would that be ready to dev? Since we need some UI

**Comment by alexrisch** [comment]
This should be done, sorry I missed closing it
