### ISSUE TITLE
Unblocking someone causes the app to crash on iOS

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#858]
Unblocking someone causes the app to crash on iOS, this was through the conversation placeholder, but it worked from the profile screen

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1727734774581189)

**Comment by alexrisch** [comment]
Did some debugging on this in Dev and am not able to repro this, but was easily reproduced in prod, I think there is a mismatch of what's in production and what's in dev
