### ISSUE TITLE
More informative alert when attempting to message non-v3 users

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#872]
(Short-term fix before https://github.com/ephemeraHQ/converse-app/issues/60)

From Peter:

I  observed something last night a few times: when people downloaded the new app, they went to make a group, then searched and added people they knew. Both saw the "<username cannot be added to a group>" which confused them as they both said, "I thought they had used XMTP".

Maybe in the early state, we could add more language to the alert like. "<username needs to be on the latest version of Converse to be added to a group">.

[Slack Message](https://xmtp-labs.slack.com/archives/C02K9T9536W/p1727786704232889)

**Comment by alexrisch** [comment]
In components/Search/NavigationChatButton.tsx when canGroupMessage is not allowed, update the text we are using
Make sure to place it in translations file as well
