### ISSUE TITLE
Enable debug button for all users

### ISSUE THREAD

**Issue by technoplato** [ephemeraHQ/converse-app#879]
Cool if we enable debug button long press for all users? Logs could be useful here

[Slack Message](https://xmtp-labs.slack.com/archives/D07MZGEU831/p1727819271873569)

**Comment by alexrisch** [comment]
Is this different from https://github.com/ephemeraHQ/converse-app/issues/817?

**Comment by alexrisch** [comment]
@saulmc are you ok with this? 
We may want to clean up some of the items in the menu, but I think generally a debug menu is helpful, especially given it takes a bit of no how to get into it anyways

**Comment by saulmc** [comment]
I am! This issue was from a convo @technoplato and I had over Slack. I think cleanup is a good idea but shouldn't block -- as long as there's no "brick my account forever" button I see no harm in shipping.
