### ISSUE TITLE
Cleanup DM invite webpage

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#880]
DM invite links need the same cleanup we did for group invites. This can be patterned directly off of the QR share sheet in the app.

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1727826359648419)

![CleanShot 2024-10-01 at 16 45 27@2x](https://github.com/user-attachments/assets/96a5189d-c270-4e85-9d30-94d28846f1e2)
![CleanShot 2024-10-01 at 16 45 33@2x](https://github.com/user-attachments/assets/814a699e-120d-42b9-9768-05ed6b693d05)

**Comment by lourou** [comment]
@saulmc @alexrisch I have updated the design implementation to mimic the group invite screen, also retrieved the preferred user profile picture from either Converse or the user's social media profiles, see the screenshot below

![CleanShot 2024-10-03 at 17 41 23@2x](https://github.com/user-attachments/assets/cb12ed50-ac5a-45c9-9873-d1a9a1ee9d4f)

**Comment by saulmc** [comment]
😍😍😍

**Comment by lourou** [comment]
![Image](https://github.com/user-attachments/assets/fb3ab966-f316-4c51-a367-afdc4a12ff62)
