### ISSUE TITLE
Display action menu on long-press of convo row

### ISSUE THREAD

**Issue by covrter** [ephemeraHQ/converse-app#933]
’Nother little QOL (quality of life) one here, also lo-pri but great if easy:
• let long-press on a convo row display an action menu (obvi can get much smarter about what goes in there later)
• this also fixes the weirdness of long-press being an immediate “pin” action
• I put convo-level Notifications in there but I don’t think we have’em yet … ignore if not

[Slack Message](https://xmtp-labs.slack.com/archives/C07NSHXK693/p1728083959454549)

**Comment by alexrisch** [comment]
There is a new build with some of these implemented

**Comment by covrter** [comment]
These are great — here's some updated guidance now that we have design system and components coming together.

- can we introduce the preview/actions directly (like reactions) rather than sliding them in from the bottom?
- style guidance:
  - https://www.loom.com/share/a2a2c46e8c734bf7b27469430b0c6d35
  - https://www.figma.com/design/p6mt4tEDltI4mypD3TIgUk/Converse-App?node-id=2853-5916&t=e61aVPFvxGke3PnG-1

**Comment by covrter** [comment]
@alexrisch please prioritize however you deem fit
