### ISSUE TITLE
Bug: Conversation context menu does not work on pinned convos

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#935]
Long press a normal conversation
Observe the context menu
Pin the conversation
Long press the pinned conversation
Observe the conversation become unpinned

Expected: Observe the context menu

[Slack Message](https://xmtp-labs.slack.com/archives/C07DX271K6V/p1728084271675179)

**Comment by alexrisch** [comment]
Fixed in V3
