### ISSUE TITLE
Feature request: Pull to refresh

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#981]
### Is your feature request related to a problem?

There is no way to manually refresh conversations and messages without killing the app.

### Describe the solution to the problem

Implement pull to refresh.

### Describe the uses cases for the feature

Get new conversations and messages when the stream is unreliable.

**Comment by alexrisch** [comment]
I think this will be a bigger part in our re-architecture 

Generally speaking the app relies on loading all data and then relying on streams afterwards

The future approach will be to fetch whenever landing on a certain page but using streams to optimistically make updates
